version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/samueltorres/r8limiter
    
    steps:
      - checkout
      - run: go get all

  publish:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run: docker build -t $DOCKER_IMAGE:latest .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push $DOCKER_IMAGE:latest


workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
